version: "3.3"

services:
  fic-python-backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    ports:
      - "8100:8100"
    network_mode: host
    
