services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: fic-backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8100:8100"
  frontend:
    build:
      context: ../frontend/fic_app
      dockerfile: Dockerfile
    container_name: fic-frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
